AZURE_TENANT_ID = "67633fcb-ac5d-4587-b639-8e7fb79691eb"
AZURE_CLIENT_ID = "80eec63f-2621-47e2-8261-456da5142f8a"
AZURE_CLIENT_SECRET = "F..8Q~wM-8uQwbaE1Pb4YGkH5f~x9iCYeQjJ8aLe"
AZURE_DICOM_ENDPOINT = "https://raisobothealthdsw-raiso-dicom.dicom.azurehealthcareapis.com"
RAISO_APIM_GATEWAY_URL= "https://raisobot-apim.azure-api.net/raisoapp"
AZURE_AI_SEARCH_ENDPOINT = "https://raiso-bot-ai-search.search.windows.net"
AZURE_AI_SEARCH_INDEX_NAME = "xray-nih-index"
AZURE_API_KEY = "MPjNHVI6xN9MCuUdtgstc3a4DLoIKZxdElbbJQjYkaAzSeAP6kir"